### ISSUE TITLE
Double-free crash when using kiro_trb_adopt in conjunction with kiro_client_get_memory

### ISSUE THREAD

**Issue by TimoDritschler** [ufo-kit/kiro#13]
When calling [kiro_trb_adopt](https://github.com/ufo-kit/kiro/blob/9f0b6da7cf20f085d2729e5433f85ffa60a6fd94/src/kiro-trb.h#L386) on memory that was returned by [kiro_client_get_memory](https://github.com/ufo-kit/kiro/blob/9f0b6da7cf20f085d2729e5433f85ffa60a6fd94/src/kiro-client.h#L179), both of them take ownership of the memory, causing a double-free situation when both of the objects get cleaned up.

I guess its kind of acceptable to say that this is a "Not my problem" bug, since both interfaces clearly specify their behavior, and I can't prevent someone from forcefully using something the wrong way, but at least I can think if there might be some easy way to prevent this pitfall.

**Comment by TimoDritschler** [comment]
There is no way to know is some other process has already freed memory that we are pointing to. I would need to entangle _trb_ and _server_ in some kind of way, for both of them to know each others memory management... Won't Fix.

**Comment by matze** [comment]
The "correct" solution would be to wrap the raw pointer in a GObject and use the reference counting mechanism to free resources when the counter is at zero. But it's probably not worth the effort.

**Comment by TimoDritschler** [comment]
Agreed
