### ISSUE TITLE
Two sequential clients in one program Segfault

### ISSUE THREAD

**Issue by Kaikas** [ufo-kit/kiro#19]
When creating a kiro client, transmitting data, disconnecting this client and creating a second client. g_main_loop_run gets a Segmentation Fault. It seems that GMainLoop has to be freed first.

**Comment by TimoDritschler** [comment]
I have checked and I can reproduce the bug. However, the ```main_loop``` **does** get cleaned up, when shutting down the client (see [here](https://github.com/ufo-kit/kiro/blob/ba80c844dd70b8dae526453abf773a918f717b40/src/kiro-client.c#L608)).
Maybe someone else still holds a reference to the ```main_loop``` or there is something else lingering around. I will have to dig into this a bit deeper.

**Comment by TimoDritschler** [comment]
I have fixed what I believe to be the problem and pushed a _fixMainLoop_ branch. Can you please check out that branch, rebase on top of it and see if this fixes your problem?

**Comment by Kaikas** [comment]
Thank you, it works now.
